export const SWAGGER_API_ROOT = 'docs';
export const SWAGGER_API_NAME = 'VERX CHALLENGE';
export const SWAGGER_API_DESCRIPTION =
  'API IMPLEMENTING AS A RESPONSE AND SOLUTION TO THE CHALLENGE OF VERX TECNOLOGIA.';
export const SWAGGER_API_CURRENT_VERSION = '1.0';
